from django.db import models

class Main(models.Model):
    id_html_builder_main = models.AutoField(primary_key=True, serialize=True)
    campaign = models.CharField(max_length=500, null=True, default=None)
    category = models.CharField(max_length=500, null=True, default=None)
    country = models.CharField(max_length=2, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)

# TODO: Usar columna (order) para mover los bloques con drag and drop y acomodar el HTML de forma que uno quiera
class Structure(models.Model):
    id_html_builder_structure = models.AutoField(primary_key=True, serialize=True)
    fk_html_builder_main = models.IntegerField(null=True)
    name = models.CharField(max_length=500, null=True, default=None)
    url_img_1 = models.CharField(max_length=1000, null=True, default=None)
    url_img_mobile_1 = models.CharField(max_length=1000, null=True)
    url_link_1 = models.CharField(max_length=1000, null=True)
    url_deeplink_1 = models.CharField(max_length=1000, null=True)
    alt_title_1 = models.CharField(max_length=1000, null=True)
    code_1 = models.CharField(max_length=500, null=True)
    url_img_2 = models.CharField(max_length=1000, null=True, default=None)
    url_link_2 = models.CharField(max_length=1000, null=True)
    url_deeplink_2 = models.CharField(max_length=1000, null=True)
    alt_title_2 = models.CharField(max_length=1000, null=True)
    code_2 = models.CharField(max_length=500, null=True)
    url_img_3 = models.CharField(max_length=1000, null=True, default=None)
    url_link_3 = models.CharField(max_length=1000, null=True)
    url_deeplink_3 = models.CharField(max_length=1000, null=True)
    alt_title_3 = models.CharField(max_length=1000, null=True)
    code_3 = models.CharField(max_length=500, null=True)
    url_img_4 = models.CharField(max_length=1000, null=True, default=None)
    url_link_4 = models.CharField(max_length=1000, null=True)
    url_deeplink_4 = models.CharField(max_length=1000, null=True)
    alt_title_4 = models.CharField(max_length=1000, null=True)
    code_4 = models.CharField(max_length=500, null=True)
    url_img_5 = models.CharField(max_length=1000, null=True, default=None)
    url_link_5 = models.CharField(max_length=1000, null=True)
    url_deeplink_5 = models.CharField(max_length=1000, null=True)
    alt_title_5 = models.CharField(max_length=1000, null=True)
    code_5 = models.CharField(max_length=500, null=True)
    url_img_6 = models.CharField(max_length=1000, null=True, default=None)
    url_link_6 = models.CharField(max_length=1000, null=True)
    url_deeplink_6 = models.CharField(max_length=1000, null=True)
    alt_title_6 = models.CharField(max_length=1000, null=True)
    code_6 = models.CharField(max_length=500, null=True)
    is_deeplink = models.CharField(max_length=500, null=True)
    order = models.CharField(max_length=500, null=True)
    tile = models.CharField(max_length=500, null=True)
    filter = models.CharField(max_length=500, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)